import { connectDb } from "../../helper/db"

export const metadata = {
    title: 'Create Next2 App',
    description: 'Generated by create next app',
  }
  
  export default function HomeLayout({ children }) {
    
    return (
        <div >
            This is Header
            {children}</div>
    )
  }